AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "bin/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "*.gemspec"

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150
  Exclude:
    - "test/**/*"

# Test files commonly use compact class definitions for brevity
Style/ClassAndModuleChildren:
  Exclude:
    - "test/**/*"

# Test method names like test_raises_error_on_400 are clearer than test_raises_error_on_four_hundred
Naming/VariableNumber:
  Exclude:
    - "test/**/*"
